source 'https://github.com/CocoaPods/Specs.git'

target 'DeepTransitionExample', :exclusive => true do
  pod "DeepTransition", :path => ".."
end

target 'DeepTransitionExampleTests', :exclusive => true do
  pod "DeepTransition", :path => ".."

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
